"""The report must state what the run DID, not what it was configured to do.

The banner this covers was itself added to fix a dishonesty defect -- the report
quoting "LLM Judge Quality 4.08" with no indication that on a keyless run the
judge is keyword matching and the generator returns a retrieved snippet. That fix
checked `if GEMINI_API_KEY:`, i.e. whether a key EXISTS.

A key can exist while the API refuses every call. An exhausted Gemini free-tier
quota returns `429 RESOURCE_EXHAUSTED` on each request, the generator logs a
warning and falls back to the retrieved template, and the run completes -- so the
report published:

    > **Judge mode: live LLM.** `GEMINI_API_KEY` was set for this run, so the
    > scores below come from real model calls.

while not one draft had been generated by a model. Same defect class as the
leaked corpus and the pre-leak-fix grounding rates, introduced by the fix for
that class, because it checked configuration instead of outcome.

Found when a real machine's quota ran out mid-run, which is the condition a
fourth review round would have constructed deliberately.
"""

import logging

import pytest

import src.drafting.generator as generator_module
import src.eval.judge as judge_module
import src.eval.report_generator as report_module
from src.models import RetrievalResult


@pytest.fixture(autouse=True)
def _clean_counters():
    generator_module.reset_llm_counters()
    judge_module.reset_judge_counters()
    yield
    generator_module.reset_llm_counters()
    judge_module.reset_judge_counters()


def _render(monkeypatch, key, gen_ok, gen_fb, jud_ok, jud_fb) -> str:
    """Drives the counters and returns what the REPORT would actually print.

    Calls `_judge_mode_note()` rather than reimplementing its branches. A test
    that reimplements a branch can pass while the branch it claims to describe
    does something else -- which is exactly what happened in round 3 with the
    ReDoS linearity test.
    """
    monkeypatch.setattr(report_module, "GEMINI_API_KEY", key)
    monkeypatch.setattr(generator_module, "LLM_CALLS_SUCCEEDED", gen_ok)
    monkeypatch.setattr(generator_module, "LLM_CALLS_FELL_BACK", gen_fb)
    monkeypatch.setattr(judge_module, "JUDGE_CALLS_SUCCEEDED", jud_ok)
    monkeypatch.setattr(judge_module, "JUDGE_CALLS_FELL_BACK", jud_fb)
    return report_module._judge_mode_note()


def test_a_key_with_every_call_failing_is_not_reported_as_a_live_llm_run(monkeypatch):
    """The exact condition that produced the false banner: key set, quota gone.

    Before this fix the report printed "Judge mode: live LLM ... the scores below
    come from real model calls" for this state.
    """
    note = _render(monkeypatch, "AIza-looks-real", 0, 124, 0, 124)
    assert "live LLM" not in note, f"still claiming a live run:\n{note}"
    assert "DETERMINISTIC FALLBACK, despite a key being set" in note
    assert "103" not in note and "124/124 generation" in note
    assert "RESOURCE_EXHAUSTED" in note, "the likeliest cause should be named"
    assert "must not be quoted as an LLM-graded result" in note
    # The figures that do NOT depend on the API must be exempted explicitly, or a
    # reader discounts the whole report.
    assert "Intent, triage, escalation-recall and latency" in note


def test_a_partially_degraded_run_is_reported_as_a_mixture(monkeypatch):
    """5 calls land before the per-minute quota bites, then everything falls back.
    A mixed population is worse than either pure one for comparison, because the
    fallback share differs between systems and between runs."""
    note = _render(monkeypatch, "AIza-looks-real", 5, 119, 5, 119)
    assert "PARTIALLY DEGRADED" in note
    assert "live LLM" not in note
    assert "119 of 124 generation calls (96%)" in note
    assert "do not compare these judge figures against another run" in note


def test_a_genuinely_live_run_is_reported_as_live(monkeypatch):
    """The other half: this must not become so cautious that a real run is
    described as degraded."""
    note = _render(monkeypatch, "AIza-looks-real", 124, 0, 124, 0)
    assert "Judge mode: live LLM." in note
    assert "124 generation, 124 judge" in note
    assert "FALLBACK" not in note and "DEGRADED" not in note


def test_a_keyless_run_is_still_reported_as_deterministic(monkeypatch):
    note = _render(monkeypatch, "", 0, 0, 0, 0)
    assert "No `GEMINI_API_KEY` was set" in note
    assert "keyword rubric" in note


def test_a_keyed_run_with_no_counter_data_refuses_to_claim_either_way(monkeypatch):
    """Report generated outside a full run: it must say it cannot tell, rather
    than defaulting to the flattering branch."""
    note = _render(monkeypatch, "AIza-looks-real", 0, 0, 0, 0)
    assert "not determined for this run" in note
    assert "live LLM" not in note


def test_the_generator_counts_a_fallback_when_the_api_refuses(monkeypatch, caplog):
    """End-to-end through the real generator, with the client raising the same
    429 the free tier returns. Asserts the counter moves AND that the fallback is
    logged -- a silent fallback is how this went unnoticed."""

    class _Quota(Exception):
        pass

    class _RefusingClient:
        class models:
            @staticmethod
            def generate_content(**_kwargs):
                raise _Quota("429 RESOURCE_EXHAUSTED: quota exceeded for free tier")

    gen = generator_module.GroundedReplyGenerator(api_key="AIza-looks-real")
    gen._llm = _RefusingClient()

    retrieval = RetrievalResult(
        snippets=["Try a force restart: hold the side button and volume down."],
        citations=[],
        similarity_scores=[0.8],
        max_similarity=0.8,
    )

    with caplog.at_level(logging.WARNING):
        gen.generate("my iphone will not turn on", "OS_SOFTWARE_TROUBLESHOOTING", retrieval)

    stats = generator_module.llm_call_stats()
    assert stats["fell_back"] == 1, f"fallback not counted: {stats}"
    assert stats["succeeded"] == 0
    assert "RESOURCE_EXHAUSTED" in caplog.text or "generation failed" in caplog.text


def test_a_keyless_generator_does_not_count_as_a_fallback():
    """"Not configured" and "configured and failing" are different facts, and
    conflating them would make a keyless run look like a degraded keyed one."""
    gen = generator_module.GroundedReplyGenerator(api_key="")
    assert gen._llm is None

    retrieval = RetrievalResult(
        snippets=["Try a force restart."], citations=[], similarity_scores=[0.8], max_similarity=0.8
    )
    gen.generate("my iphone will not turn on", "OS_SOFTWARE_TROUBLESHOOTING", retrieval)

    stats = generator_module.llm_call_stats()
    assert stats == {"succeeded": 0, "fell_back": 0, "attempted": 0}, stats


def test_counters_reset_between_runs():
    """A second run in one process must not inherit the first run's successes and
    under-report degradation."""
    generator_module.LLM_CALLS_SUCCEEDED = 50
    judge_module.JUDGE_CALLS_FELL_BACK = 7
    generator_module.reset_llm_counters()
    judge_module.reset_judge_counters()
    assert generator_module.llm_call_stats()["attempted"] == 0
    assert judge_module.judge_call_stats()["attempted"] == 0


# ---------------------------------------------------------------------------
# The same lesson, one level out: the report must record the CONFIGURATION that
# produced its numbers, not just the outcome of the LLM calls.
# ---------------------------------------------------------------------------
def test_the_report_records_whether_live_link_checking_was_on(monkeypatch):
    """Two runs of identical code gave triage 63.7% and 58.9%, and P95 36ms and
    2188ms, because of ENABLE_LIVE_LINK_CHECK plus whether the machine could reach
    the internet. The corpus is 2017-2018 and its t.co links are dead, so with
    verification on and a real network those become genuine guardrail violations.

    Neither number was wrong. The report quoting one without saying which
    configuration produced it was.
    """
    import src.drafting.guardrails as guardrails_module

    note = report_module._run_configuration_note()
    assert "ENABLE_LIVE_LINK_CHECK" in note
    assert "RAG_CORPUS_MAX_RECORDS" in note
    assert "MIN_INTENT_CONFIDENCE" in note
    assert "MIN_RETRIEVAL_SIMILARITY" in note

    # With the flag off, it must say nothing was fetched rather than stay silent.
    monkeypatch.setattr(guardrails_module, "LINK_CHECK_OUTCOMES", {})
    from src import config as config_module

    monkeypatch.setattr(config_module, "ENABLE_LIVE_LINK_CHECK", False)
    assert "was **off** for this run" in report_module._run_configuration_note()


def test_a_link_check_that_verified_nothing_says_so(monkeypatch):
    """The trap this closes: switching the flag ON in a network-blocked
    environment costs runtime and verifies NOTHING, because an inconclusive check
    passes rather than fail-closing. A reader seeing "link verification: on" would
    reasonably assume links were verified.
    """
    import src.drafting.guardrails as guardrails_module
    from src import config as config_module

    monkeypatch.setattr(config_module, "ENABLE_LIVE_LINK_CHECK", True)
    monkeypatch.setattr(guardrails_module, "LINK_CHECK_OUTCOMES", {"inconclusive": 102})
    note = report_module._run_configuration_note()
    assert "Every check was inconclusive" in note
    assert "verified nothing" in note


def test_failed_link_checks_are_flagged_as_making_the_numbers_incomparable(monkeypatch):
    import src.drafting.guardrails as guardrails_module
    from src import config as config_module

    monkeypatch.setattr(config_module, "ENABLE_LIVE_LINK_CHECK", True)
    monkeypatch.setattr(guardrails_module, "LINK_CHECK_OUTCOMES", {"broken": 30, "ok": 12})
    note = report_module._run_configuration_note()
    assert "30 link(s) failed verification" in note
    assert "NOT comparable" in note
    assert "corpus age, not a regression" in note
